kind: pipeline
type: docker
name: default

steps:
  - name: install
    image: node:12.12.0
    commands:
      - npm install

  - name: build
    image: node:12.12.0
    commands:
        - npm run prebuild
        - npm run build
    
  - name: kaniko
    image: banzaicloud/drone-kaniko
    settings:
      environment:
        REGISTRY: 
          from_secret: REGISTRY
        USERNAME:
          from_secret: DOCKER_USERNAME
        TOKEN: 
          from_secret: DOCKER_TOKEN
      repo: mspr-ci-back
      tags: latest

  - name: testing
    image: node:12.12.0
    group: testing
    commands:
      - npm run test

  - name: lint
    image: node:12.12.0
    group: testing
    commands:
      - npm run lint

  - name: coverage
    image: node:12.12.0
    group: testing
    commands:  
      - npm run test:cov