kind: pipeline
type: docker
name: default

steps:
  - name: install
    image: node:12.16.1
    commands:
      - npm install

  - name: doc
    image: node:12.16.1
    commands:
      - npm run doc
    depends_on: [install]
    
  - name: kaniko
    image: banzaicloud/drone-kaniko
    settings:
      username:
        from_secret: DOCKER_USERNAME
      password: 
        from_secret: DOCKER_TOKEN
      registry: registry.gitlab.com
      repo: mspr-ci1/mspr-ci-back
      tags: 0.0.1
    depends_on: [doc]

  - name: testing
    image: node:12.16.1
    group: testing
    commands:
      - npm run test
    depends_on: [kaniko]

  - name: lint
    image: node:12.16.1
    group: testing
    commands:
      - npm run lint
    depends_on: [kaniko]

  - name: coverage
    image: node:12.16.1
    group: testing
    commands:  
      - npm run test:cov
    depends_on: [kaniko]

  - name: deploy
    image: caprover/cli-caprover:latest
    commands:
      #- git checkout -b release-${DRONE_TAG}
      - npx caprover deploy -h $CAPROVER_DOMAIN -p $CAPROVER_PASSWORD -a $CAPROVER_APPNAME -b documentation/tech-doc
      #Add -b release-${DRONE_TAG} to push and deploy on tag
    environment:
      CAPROVER_DOMAIN:
        from_secret: CAPROVER_DOMAIN
      CAPROVER_APPNAME:
        from_secret: CAPROVER_APPNAME
      CAPROVER_PASSWORD:
        from_secret: CAPROVER_PASSWORD
    depends_on: [testing, lint, coverage, kaniko]
    #when:
    #  event: tag 