pipeline:
  restore-cache:
    image: drillster/drone-volume-cache
    restore: true
    mount:
      - ./node_modules
    volumes:
      - /var/lib/drone:/data

  install:
    image: node:12.12.0
    commands:
      - npm install

  build:
    image: node:12.12.0
    commands:
        - npm run prebuild
        - npm run build

  build-image:
    image: docker:19.03.1
    variables:
        DOCKER_DRIVER: overlay2
        DOCKER_TLS_CERTDIR: ''
    services:
        - docker:19.03.1-dind
    commands:
        - sudo docker build -t aya-market-back:0.0.1 .
        - sudo docker build -t registry.gitlab.com/mspr-ci1/mspr-ci-back .
    artifacts:
        paths:
        - Dockerfile

  testing:
    image: node:12.12.0
    group: testing
    commands:
      - npm run test

  lint:
    image: node:12.12.0
    group: testing
    commands:
      - npm run lint

  coverage:
    image: node:12.12.0
    group: testing
    commands:  
      - npm run test:cov
