pipeline:
  restore-cache:
    image: drillster/drone-volume-cache
    restore: true
    mount:
      - ./node_modules
    volumes:
      - /var/lib/drone:/data

  install:
    image: node:12.12.0
    commands:
      - npm install

  build:
    image: node:12.12.0
    commands:
        - npm run prebuild
        - npm run build

  testing:
    image: node:12.12.0
    group: testing
    commands:
      - npm run test

  lint:
    image: node:12.12.0
    group: testing
    commands:
      - npm run lint

  coverage:
    image: node:12.12.0
    group: testing
    commands:  
      - npm run test:cov
